### ISSUE TITLE
SBB - role modify of higher roles

### ISSUE THREAD

**Issue by rettichlp** [rettichlp/shantybot#15]
```
net.dv8tion.jda.api.exceptions.HierarchyException: Can't modify a role with higher or equal highest role than yourself! Role: Role:- Mitglied(id=802943477385134141)
        at net.dv8tion.jda.internal.entities.GuildImpl.checkPosition(GuildImpl.java:2031) ~[JDA-5.0.2.jar!/:5.0.2]
        at net.dv8tion.jda.internal.entities.GuildImpl.addRoleToMember(GuildImpl.java:1688) ~[JDA-5.0.2.jar!/:5.0.2]
        at de.rettichlp.shantybot.common.services.RoleSyncService.lambda$deleteOldLogEntries$4(RoleSyncService.java:36) ~[!/:1.1.1]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[na:na]
        at de.rettichlp.shantybot.common.services.RoleSyncService.lambda$deleteOldLogEntries$7(RoleSyncService.java:42) ~[!/:1.1.1]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[na:na]
        at de.rettichlp.shantybot.common.services.RoleSyncService.deleteOldLogEntries(RoleSyncService.java:28) ~[!/:1.1.1]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.11.jar!/:6.1.11]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.11.jar!/:6.1.11]
        at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.13.2.jar!/:1.13.2]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.11.jar!/:6.1.11]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.11.jar!/:6.1.11]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96) ~[spring-context-6.1.11.jar!/:6.1.11]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

**Comment by rettichlp** [comment]
The bot role was moved in a higher position than the member role and tested.
